// Shared plumbing for on-board CYNQ tools: the dfs_accel register map, the
// cases.json parser, and the raw result layout read back from the IP.
// Used by validate_cynq.cpp (#67, correctness) and benchmark_cynq.cpp (#91,
// throughput) so both stay in sync with the same schema without duplicating
// ~150 lines of parsing code between them.
//
// No JSON library dependency: cases.json is generated by our own
// export_cases.cpp with a fixed, known schema (flat objects, only
// strings/ints/int-arrays), so a small parser tailored to exactly that
// schema is simpler and more honest than pulling in a general-purpose
// library for it.
#ifndef DFS_ONBOARD_DFS_ACCEL_CASE_IO_H_
#define DFS_ONBOARD_DFS_ACCEL_CASE_IO_H_

#include <cctype>
#include <cstdint>
#include <stdexcept>
#include <string>
#include <vector>

// dfs_accel_0's AXI-Lite control base address (from dfs_system.hwh,
// MEMRANGE for INSTANCE="dfs_accel_0", SLAVEBUSINTERFACE="s_axi_control").
constexpr uint64_t kAccelAddr = 0x80000000;

// Register offsets within the IP, from xdfs_accel_hw.h (Vitis HLS driver).
constexpr uint64_t kAddrGridIn = 0x10;
constexpr uint64_t kAddrWordsIn = 0x18;
constexpr uint64_t kAddrResultOut = 0x20;
constexpr uint64_t kAddrRows = 0x28;
constexpr uint64_t kAddrCols = 0x30;
constexpr uint64_t kAddrMode = 0x38;
constexpr uint64_t kAddrFlags = 0x40;
constexpr uint64_t kAddrNumWords = 0x48;

namespace tinyjson {

struct Case {
  std::string algorithm;
  std::string name;
  uint32_t mode = 0, flags = 0, rows = 0, cols = 0, num_words = 0;
  std::vector<int> grid;
  std::vector<int> words;
  long expected_value = 0;
  unsigned long long expected_expanded_nodes = 0;
  unsigned long long expected_visited_cells = 0;
  unsigned long long expected_peak_stack_depth = 0;
};

class Parser {
 public:
  explicit Parser(const std::string& text) : s_(text), pos_(0) {}

  std::vector<Case> ParseCases() {
    std::vector<Case> cases;
    SkipWs();
    Expect('[');
    SkipWs();
    if (Peek() == ']') {
      ++pos_;
      return cases;
    }
    while (true) {
      SkipWs();
      cases.push_back(ParseCase());
      SkipWs();
      if (Peek() == ',') {
        ++pos_;
        continue;
      }
      break;
    }
    SkipWs();
    Expect(']');
    return cases;
  }

 private:
  const std::string& s_;
  size_t pos_;

  char Peek() { return s_[pos_]; }
  void Expect(char c) {
    if (s_[pos_] != c)
      throw std::runtime_error(std::string("expected '") + c + "' at " +
                               std::to_string(pos_));
    ++pos_;
  }
  void SkipWs() {
    while (pos_ < s_.size() &&
          std::isspace(static_cast<unsigned char>(s_[pos_])))
      ++pos_;
  }
  std::string ParseString() {
    Expect('"');
    std::string out;
    while (s_[pos_] != '"') {
      if (s_[pos_] == '\\') {
        ++pos_;
      }
      out.push_back(s_[pos_]);
      ++pos_;
    }
    Expect('"');
    return out;
  }
  long ParseInt() {
    size_t start = pos_;
    if (s_[pos_] == '-') ++pos_;
    while (pos_ < s_.size() &&
          std::isdigit(static_cast<unsigned char>(s_[pos_])))
      ++pos_;
    return std::stol(s_.substr(start, pos_ - start));
  }
  std::vector<int> ParseIntArray() {
    std::vector<int> out;
    Expect('[');
    SkipWs();
    if (Peek() == ']') {
      ++pos_;
      return out;
    }
    while (true) {
      SkipWs();
      out.push_back(static_cast<int>(ParseInt()));
      SkipWs();
      if (Peek() == ',') {
        ++pos_;
        continue;
      }
      break;
    }
    SkipWs();
    Expect(']');
    return out;
  }
  Case ParseCase() {
    Case c;
    Expect('{');
    while (true) {
      SkipWs();
      std::string key = ParseString();
      SkipWs();
      Expect(':');
      SkipWs();
      if (key == "algorithm") {
        c.algorithm = ParseString();
      } else if (key == "case") {
        c.name = ParseString();
      } else if (key == "mode") {
        c.mode = static_cast<uint32_t>(ParseInt());
      } else if (key == "flags") {
        c.flags = static_cast<uint32_t>(ParseInt());
      } else if (key == "rows") {
        c.rows = static_cast<uint32_t>(ParseInt());
      } else if (key == "cols") {
        c.cols = static_cast<uint32_t>(ParseInt());
      } else if (key == "num_words") {
        c.num_words = static_cast<uint32_t>(ParseInt());
      } else if (key == "grid") {
        c.grid = ParseIntArray();
      } else if (key == "words") {
        c.words = ParseIntArray();
      } else if (key == "expected_value") {
        c.expected_value = ParseInt();
      } else if (key == "expected_expanded_nodes") {
        c.expected_expanded_nodes =
            static_cast<unsigned long long>(ParseInt());
      } else if (key == "expected_visited_cells") {
        c.expected_visited_cells = static_cast<unsigned long long>(ParseInt());
      } else if (key == "expected_peak_stack_depth") {
        c.expected_peak_stack_depth =
            static_cast<unsigned long long>(ParseInt());
      } else {
        throw std::runtime_error("cases.json: unknown key '" + key + "'");
      }
      SkipWs();
      if (Peek() == ',') {
        ++pos_;
        continue;
      }
      break;
    }
    SkipWs();
    Expect('}');
    return c;
  }
};

}  // namespace tinyjson

// Raw layout of dfs_accel's result register: value, then the three
// traversal counters, in that order -- matches the four uint32_t words
// read back from kAddrResultOut.
struct RunResult {
  uint32_t value, expanded_nodes, visited_cells, peak_stack_depth;
};

#endif  // DFS_ONBOARD_DFS_ACCEL_CASE_IO_H_
