// On-board validation of dfs_accel against the 21 golden cases (issue #67),
// using CYNQ instead of PYNQ -- see README.md for why (PYNQ 3.x needs
// pyxrt, which isn't available on this board's XRT install).
//
// Mirrors src/hls/tb/dfs_accel_tb.cpp's cosim check (#63): same 21 cases,
// same pass/fail bar -- a case only fails if its result VALUE disagrees
// with cases.json's expected_value; a traversal-counter mismatch alone is
// reported (status "ok*") but doesn't fail the case.
//
// Usage: ./validate_cynq <bitstream.bit> <cases.json>
//
// No JSON library dependency: cases.json is generated by our own
// export_cases.cpp with a fixed, known schema (flat objects, only
// strings/ints/int-arrays), so a ~100-line parser tailored to exactly that
// schema is simpler and more honest than pulling in a general-purpose
// library for it.

#include <cctype>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include <cynq/cynq.hpp>

using namespace cynq;  // NOLINT

// dfs_accel_0's AXI-Lite control base address (from dfs_system.hwh,
// MEMRANGE for INSTANCE="dfs_accel_0", SLAVEBUSINTERFACE="s_axi_control").
constexpr uint64_t kAccelAddr = 0x80000000;

// Register offsets within the IP, from xdfs_accel_hw.h (Vitis HLS driver).
constexpr uint64_t kAddrGridIn = 0x10;
constexpr uint64_t kAddrWordsIn = 0x18;
constexpr uint64_t kAddrResultOut = 0x20;
constexpr uint64_t kAddrRows = 0x28;
constexpr uint64_t kAddrCols = 0x30;
constexpr uint64_t kAddrMode = 0x38;
constexpr uint64_t kAddrFlags = 0x40;
constexpr uint64_t kAddrNumWords = 0x48;

namespace tinyjson {

struct Case {
  std::string algorithm;
  std::string name;
  uint32_t mode = 0, flags = 0, rows = 0, cols = 0, num_words = 0;
  std::vector<int> grid;
  std::vector<int> words;
  long expected_value = 0;
  unsigned long long expected_expanded_nodes = 0;
  unsigned long long expected_visited_cells = 0;
  unsigned long long expected_peak_stack_depth = 0;
};

class Parser {
 public:
  explicit Parser(const std::string& text) : s_(text), pos_(0) {}

  std::vector<Case> ParseCases() {
    std::vector<Case> cases;
    SkipWs();
    Expect('[');
    SkipWs();
    if (Peek() == ']') {
      ++pos_;
      return cases;
    }
    while (true) {
      SkipWs();
      cases.push_back(ParseCase());
      SkipWs();
      if (Peek() == ',') {
        ++pos_;
        continue;
      }
      break;
    }
    SkipWs();
    Expect(']');
    return cases;
  }

 private:
  const std::string& s_;
  size_t pos_;

  char Peek() { return s_[pos_]; }
  void Expect(char c) {
    if (s_[pos_] != c)
      throw std::runtime_error(std::string("expected '") + c + "' at " +
                               std::to_string(pos_));
    ++pos_;
  }
  void SkipWs() {
    while (pos_ < s_.size() &&
          std::isspace(static_cast<unsigned char>(s_[pos_])))
      ++pos_;
  }
  std::string ParseString() {
    Expect('"');
    std::string out;
    while (s_[pos_] != '"') {
      if (s_[pos_] == '\\') {
        ++pos_;
      }
      out.push_back(s_[pos_]);
      ++pos_;
    }
    Expect('"');
    return out;
  }
  long ParseInt() {
    size_t start = pos_;
    if (s_[pos_] == '-') ++pos_;
    while (pos_ < s_.size() &&
          std::isdigit(static_cast<unsigned char>(s_[pos_])))
      ++pos_;
    return std::stol(s_.substr(start, pos_ - start));
  }
  std::vector<int> ParseIntArray() {
    std::vector<int> out;
    Expect('[');
    SkipWs();
    if (Peek() == ']') {
      ++pos_;
      return out;
    }
    while (true) {
      SkipWs();
      out.push_back(static_cast<int>(ParseInt()));
      SkipWs();
      if (Peek() == ',') {
        ++pos_;
        continue;
      }
      break;
    }
    SkipWs();
    Expect(']');
    return out;
  }
  Case ParseCase() {
    Case c;
    Expect('{');
    while (true) {
      SkipWs();
      std::string key = ParseString();
      SkipWs();
      Expect(':');
      SkipWs();
      if (key == "algorithm") {
        c.algorithm = ParseString();
      } else if (key == "case") {
        c.name = ParseString();
      } else if (key == "mode") {
        c.mode = static_cast<uint32_t>(ParseInt());
      } else if (key == "flags") {
        c.flags = static_cast<uint32_t>(ParseInt());
      } else if (key == "rows") {
        c.rows = static_cast<uint32_t>(ParseInt());
      } else if (key == "cols") {
        c.cols = static_cast<uint32_t>(ParseInt());
      } else if (key == "num_words") {
        c.num_words = static_cast<uint32_t>(ParseInt());
      } else if (key == "grid") {
        c.grid = ParseIntArray();
      } else if (key == "words") {
        c.words = ParseIntArray();
      } else if (key == "expected_value") {
        c.expected_value = ParseInt();
      } else if (key == "expected_expanded_nodes") {
        c.expected_expanded_nodes =
            static_cast<unsigned long long>(ParseInt());
      } else if (key == "expected_visited_cells") {
        c.expected_visited_cells = static_cast<unsigned long long>(ParseInt());
      } else if (key == "expected_peak_stack_depth") {
        c.expected_peak_stack_depth =
            static_cast<unsigned long long>(ParseInt());
      } else {
        throw std::runtime_error("cases.json: unknown key '" + key + "'");
      }
      SkipWs();
      if (Peek() == ',') {
        ++pos_;
        continue;
      }
      break;
    }
    SkipWs();
    Expect('}');
    return c;
  }
};

}  // namespace tinyjson

struct RunResult {
  uint32_t value, expanded_nodes, visited_cells, peak_stack_depth;
};

RunResult RunCase(std::shared_ptr<IAccelerator> accel,
                  std::shared_ptr<IDataMover> mover,
                  const tinyjson::Case& c) {
  // Cacheable, not Dual: on Zynq there's one shared DDR, not a separate
  // "device" region needing a real DMA IP (this design has none -- m_axi
  // goes straight through smartconnect to the PS HP port). Dual +
  // mover->Upload()/Download() hangs indefinitely here, presumably because
  // the XRT DataMover backend expects a real DMA IP at kAccelAddr.
  auto grid_buf = mover->GetBuffer(c.grid.size(), 0, MemoryType::Cacheable);
  auto words_buf = mover->GetBuffer(c.words.size(), 0, MemoryType::Cacheable);
  auto result_buf =
      mover->GetBuffer(4 * sizeof(uint32_t), 0, MemoryType::Cacheable);

  uint8_t* grid_host = grid_buf->HostAddress<uint8_t>().get();
  for (size_t i = 0; i < c.grid.size(); ++i)
    grid_host[i] = static_cast<uint8_t>(c.grid[i]);
  uint8_t* words_host = words_buf->HostAddress<uint8_t>().get();
  for (size_t i = 0; i < c.words.size(); ++i)
    words_host[i] = static_cast<uint8_t>(c.words[i]);

  grid_buf->Sync(SyncType::HostToDevice);
  words_buf->Sync(SyncType::HostToDevice);

  accel->Attach(kAddrGridIn, grid_buf);
  accel->Attach(kAddrWordsIn, words_buf);
  accel->Attach(kAddrResultOut, result_buf);

  uint32_t rows = c.rows, cols = c.cols, mode = c.mode, flags = c.flags,
          num_words = c.num_words;
  accel->Attach(kAddrRows, &rows, RegisterAccess::WO);
  accel->Attach(kAddrCols, &cols, RegisterAccess::WO);
  accel->Attach(kAddrMode, &mode, RegisterAccess::WO);
  accel->Attach(kAddrFlags, &flags, RegisterAccess::WO);
  accel->Attach(kAddrNumWords, &num_words, RegisterAccess::WO);

  accel->Start(StartMode::Once);
  accel->Sync();

  result_buf->Sync(SyncType::DeviceToHost);
  uint32_t* result = result_buf->HostAddress<uint32_t>().get();

  return {result[0], result[1], result[2], result[3]};
}

int main(int argc, char** argv) {
  if (argc != 3) {
    std::fprintf(stderr, "usage: %s <bitstream.bit> <cases.json>\n", argv[0]);
    return 1;
  }
  const std::string bitstream = argv[1];
  const std::string cases_path = argv[2];

  std::ifstream f(cases_path);
  if (!f) {
    std::fprintf(stderr, "cannot open %s\n", cases_path.c_str());
    return 1;
  }
  std::stringstream ss;
  ss << f.rdbuf();

  std::vector<tinyjson::Case> cases;
  try {
    cases = tinyjson::Parser(ss.str()).ParseCases();
  } catch (const std::exception& e) {
    std::fprintf(stderr, "cases.json parse error: %s\n", e.what());
    return 1;
  }

  std::printf("----- Initialising platform -----\n");
  auto platform = IHardware::Create(HardwareArchitecture::UltraScale, bitstream);

  // build_bitstream.tcl (#67) built this at 200 MHz -- CYNQ doesn't read
  // the .hwh, so it doesn't know that; set it explicitly.
  auto clocks = platform->GetClocks();
  for (size_t i = 0; i < clocks.size(); ++i)
    clocks[i] = (i == 0) ? 200.f : -1.f;
  platform->SetClocks(clocks);

  // Read back rather than trust the call silently succeeded -- confirms
  // what CYNQ itself now believes clock 0 is set to.
  const auto confirmed_clocks = platform->GetClocks();
  if (!confirmed_clocks.empty())
    std::printf("Clock 0 after SetClocks: %.3f MHz\n", confirmed_clocks[0]);

  auto accel = platform->GetAccelerator(kAccelAddr);
  auto mover = platform->GetDataMover(kAccelAddr);

  int total = 0, failures = 0, counter_mismatches = 0;
  std::printf("%-32s %-18s %8s %8s  status\n", "algorithm", "case", "expect",
             "hw");

  for (const auto& c : cases) {
    ++total;
    RunResult r = RunCase(accel, mover, c);

    const bool value_ok = static_cast<long>(r.value) == c.expected_value;
    const bool counters_ok =
        r.expanded_nodes == c.expected_expanded_nodes &&
        r.visited_cells == c.expected_visited_cells &&
        r.peak_stack_depth == c.expected_peak_stack_depth;

    if (!value_ok)
      ++failures;
    else if (!counters_ok)
      ++counter_mismatches;

    const char* status = !value_ok ? "FAIL" : (counters_ok ? "ok" : "ok*");
    std::printf("%-32s %-18s %8ld %8u  %s\n", c.algorithm.c_str(),
               c.name.c_str(), c.expected_value, r.value, status);
  }

  std::printf("\n%d/%d cases match the golden result (on-board)\n",
             total - failures, total);
  if (counter_mismatches > 0)
    std::printf("%d case(s) marked ok* differ in traversal counters\n",
               counter_mismatches);

  return failures == 0 ? 0 : 1;
}
